export const prop_types =[
    'Apartment',
    'Bed & Breakfast', 
    'Loft', 
    'Townhouse', 
    'Condominium', 
    'House', 
    'Other'
]

export const room_types = ['Shared room', 'Entire home/apt', 'Private room']

export const boroughs = [
    'Manhattan', 
    'Brooklyn', 
    'Bronx', 
    'Queens', 
    'Staten Island']
    
export const neighborhoods = [
    'Jackson Heights',
    'Cypress Hills',
    'Sheepshead Bay',
    "Hell's Kitchen",
    'Harlem',
    'Theater District',
    'East Village',
    'St. Albans',
    'East Harlem',
    'Arverne',                                             
    'Upper West Side',
    'Washington Heights',
    'Long Island City',
    'Financial District',
    'Upper East Side',
    'Midtown', 
    'Kips Bay', 
    'Gramercy',
    'Astoria', 
    'Lower East Side',                                             
    'Chelsea', 
    'Woodside', 
    'Bushwick', 
    'Williamsburg', 
    'West Village', 
    'Boerum Hill',
    'Sunset Park', 
    'Fort Greene', 
    'Greenwich Village', 
    'Prospect Heights', 
    'Morningside Heights',
    'Park Slope', 
    'Nolita',
    'Flatlands', 
    'Brighton Beach',
    'Canarsie',  
    'Rockaway Beach', 
    'Fort Hamilton', 
    'Crown Heights',  
    'Flatbush', 
    'Murray Hill',
    'Inwood', , 
    'Norwood', 
    'Corona', 
    'Bedford-Stuyvesant', 
    'Flushing',  
    'Jamaica', 
    'Mott Haven', 
    'East Flatbush', 
    'Little Italy', 
    'Flatiron District', 
    'Clinton Hill', 
    'Forest Hills', 
    'East Elmhurst',
    'Greenpoint', 
    'Prospect-Lefferts Gardens', 
    'SoHo', 
    'Downtown Brooklyn',
    'Battery Park City', 
    'Concourse Village', 
    'Roosevelt Island', 
    'Shore Acres', 
    'Midwood', 
    'Borough Park',
    'Kensington', 
    'Maspeth', 
    'Elmhurst', 
    'Ditmars Steinway', 
    'Woodhaven',
    'Marble Hill', 
    'Ridgewood',
    'Rego Park', 
    'Kew Gardens', 
    'Sunnyside', 
    'Brownsville',
    'Parkchester', 
    'Bronxdale', 
    'Riverdale',
    'Kingsbridge', 
    'Queens Village', 
    'Far Rockaway', 
    'Middle Village',
    'Concourse', 
    'Gowanus',  
    'Bensonhurst',  
    'Gravesend', 
    'Windsor Terrace', 
    'Chinatown', 
    'Clason Point',  
    'Coney Island', 
    'East New York', 
    'Cambria Heights', 
    'NoHo', 
    'Rockaway Park', 
    'Spuyten Duyvil', 
    'Schuylerville',  
    'Mount Eden', 
    'Springfield Gardens', 
    'Rosedale', 
    'Richmond Hill',  
    'Todt Hill', 
    'Jamaica Estates', 
    'Two Bridges', 
    'Cobble Hill', 
    'South Slope', 
    'Carroll Gardens', 
    'Red Hook', 
    'Tribeca', 
    'Central Park', 
    'Forest Park', 
    'Fresh Meadows', 
    'College Point', 
    'Stuyvesant Town', 
    'Tottenville',  
    'South Beach', 
    'Civic Center', 
    'Brooklyn Heights',  
    'Belle Harbor', 
    'Whitestone', 
    'Neponsit', 
    'St. George', 
    'Graniteville', 
    'Arrochar', 
    'DUMBO',  
    'Vinegar Hill',  
    'Columbia St',  
    'Bergen Beach', 
    'Navy Yard', 
    'Bayside', 
    'Mount Hope', 
    'Stapleton',  
    'Howard Beach', 
    'Bay Ridge', 
    'Lighthouse Hill', 
    'Mariners Harbor', 
    'Randall Manor', 
    'Wakefield', 
    'Tompkinsville', 
    'Bath Beach', 
    'Dyker Heights', 
    'Prospect Park', 
    'Dongan Hills', 
    'South Ozone Park', 
    'Kew Gardens Hills', 
    'Laurelton', 
    'Port Morris', 
    'Melrose', 
    'Eastchester', 
    'Pelham Gardens', 
    'Manhattan Beach',
    'Concord', 
    'Park Hill', 
    'Marine Park', 
    'Fordham', 
    'Bellerose', 
    'Jamaica Hills', 
    'Pelham Bay', 
    'Allerton',  
    'City Island', 
    'Huguenot', 
    'Bay Terrace', 
    'Claremont Village', 
    'Midland Beach', 
    'Clifton', 
    'Glendale',
    'Longwood',
    'Unionport', 
    'East Morrisania',  
    'Latourette Park', 
    'Howland Hook', 
    'Holliswood',  
    'New Brighton',  
    'Crotona Park', 
    'Highbridge', 
    'Van Cortlandt Park', 
    'Briarwood', 
    'Ozone Park', 
    'Silver Lake',  
    'West Brighton', 
    'Fieldston', 
    'Woodlawn', 
    'Williamsbridge', 
    'Castle Hill', 
    'Throgs Neck', 
    'Great Kills', 
    'Richmondtown', 
    'Grant City', 
    'Castleton Corners', 
    'Bronx Park', 
    'Soundview', 
    'Baychester', 
    'Emerson Hill', 
    'Eltingville', 
    'University Heights',
    'Hollis Hills', 
    'Sea Gate', 
    'Bayswater', 
    'Belmont', 
    'Edenwald', 
    'Glen Oaks', 
    'Green-Wood Cemetery',
    'Port Richmond',  
    'LaGuardia Airport', 
    'Hunts Point',  
    "Randall's Island",
    'North Riverdale', 
    'Douglaston', 
    'Arden Heights', 
    'New Springville', 
    'Edgemere', 
    'Grymes Hill', 
    'Flushing Meadows Corona Park', 
    'Hollis', 
    'Morris Heights', 
    'Westchester Square', 
    'Morrisania', 
    'Co-op City', 
    'Tremont', 
    'Van Nest', 
    'West Farms'
]
 
 